### PR TITLE
Add example for crypto, forex, indices, options, and stocks

### PR DESCRIPTION
**Pull request by justinpolygon**
Here are the demo code snippets for crypto, forex, indices, options, and stocks. I've tested these with 6.2.2 and 7.1.1 so they should work. Indices doesn't work on 6.2.2 though since none of the backend code is there.

### CODE REVIEW

**Review by tharnach — COMMENTED** [review]
This is awesome! My only feedback is that we don't need dynamic imports here and as an example, it could lead to confusion.

**Comment by justinpolygon** [comment]
Thanks for checking this out @tharnach. I'm preface this with I'm a total javascript newb. Originally, I had all the examples looking like this:

```javascript
const { restClient } = require('@polygon.io/client-js');
const rest = restClient("API KEY");

	rest.crypto.aggregates("X:BTCUSD", 1, "day", "2023-01-30", "2023-02-03").then((data) => {
		console.log(data);
	}).catch(e => {
		console.error('An error happened:', e);
	});
```

That worked great for 6.x, but when I tried to run that on 7.x for the Indices, then I encountered this error:

```
/root/polygon/test-622.js:1
const { restClient } = require('@polygon.io/client-js');
                       ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /root/polygon/node_modules/@polygon.io/client-js/lib/main.js from /root/polygon/test-622.js not supported.
Instead change the require of main.js in /root/polygon/test-622.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/root/polygon/test-622.js:1:24) {
  code: 'ERR_REQUIRE_ESM'
}
```

So, that's how I ended up landing on the following pattern that works for 6.x and 7.x.

```javascript
import('@polygon.io/client-js').then(({ restClient }) => {
  const rest = restClient('API KEY', 'https://api.polygon.io');

	// https://polygon.io/docs/crypto/get_v2_aggs_ticker__cryptoticker__range__multiplier___timespan___from___to
	rest.crypto.aggregates("X:BTCUSD", 1, "day", "2023-01-30", "2023-02-03").then((data) => {
		console.log(data);
	}).catch(e => {
		console.error('An error happened:', e);
	});

});
```

**Comment by tharnach** [comment]
Ah, I see. Yeah, we moved to ESModules in version 7. Previously it was in CommonJS. The two aren't exactly interchangeable, which is where your complications are coming from.

It might be worth it to separate concerns here and have a long-running v6 branch that has examples and tests that work for that version so we're not trying to find something that works for both.

**Comment by justinpolygon** [comment]
Got it, thanks. Is this style/syntax correct for 7.x+? I'm just wondering if this works at all or we need to change it.

**Comment by tharnach** [comment]
> Got it, thanks. Is this style/syntax correct for 7.x+? I'm just wondering if this works at all or we need to change it.

What you have would work, but I think a more typical usage would be something like this (pseudocode):

```js
import { restClient } from '@polygon.io/client-js'

const rest = restClient(API_KEY, "https://api.polygon.io");

rest.indices.previousClose("I:SPX").then((data) => {
   console.log(data);
}).catch(e => {
   console.error('An error happened:', e.message);
});
```

**Comment by justinpolygon** [comment]
Thanks for all the reviews and works here @timetraveler328 and @tharnach. I've tested these examples with `v6.2.2` and `v7.2.0` and they work across both without issue. Mind doing another review here and hopefully we can wrap this up.

**Review by tharnach — APPROVED** [review]

**Pull request merged**
